package com.travel.agent.core.etl;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * MediacrawlerConfigWriter 的单元测试。
 *
 * <p>重点验证关键词配置预览的安全性：英文逗号、换行和双引号不能破坏 Python 字符串。</p>
 */
class MediacrawlerConfigWriterTest {

    @Test
    void renderKeywordsConfigBuildsPythonAssignment() {
        MediacrawlerConfigWriter writer = new MediacrawlerConfigWriter();

        String config = writer.renderKeywordsConfig(List.of("卢浮宫 攻略", "罗马斗兽场 避坑"));

        assertThat(config).contains("KEYWORDS = \"卢浮宫 攻略,罗马斗兽场 避坑\"");
        assertThat(config).contains("Generated by AgentProjectTrip");
    }

    @Test
    void sanitizeKeywordsRemovesUnsafeSeparators() {
        MediacrawlerConfigWriter writer = new MediacrawlerConfigWriter();

        List<String> keywords = writer.sanitizeKeywords(List.of("巴黎,小众", "罗马\"门票", "瑞士\n交通"));

        assertThat(keywords)
                .containsExactly("巴黎 小众", "罗马 门票", "瑞士 交通");
    }
}
