package com.travel.agent.core.etl;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * MediaCrawler 配置片段生成器（Core ETL 层 - base_config.py 安全预览）。
 *
 * <p>系统架构位置：CrawlTaskService -> <b>MediacrawlerConfigWriter</b> -> MediaCrawler base_config.py(KEYWORDS)</p>
 *
 * <p>职责：
 * <ul>
 *   <li>把审核后的关键词列表渲染成 MediaCrawler 可识别的 {@code KEYWORDS = "..."} 配置片段。</li>
 *   <li>提供人工审查用预览文本，避免后端直接改外部爬虫项目。</li>
 *   <li>后续可以扩展为带备份、差异检查和路径校验的安全写文件能力。</li>
 * </ul>
 * </p>
 *
 * <p>TODO(stage14-media-crawler-config-writer-apply)：如需真正写入
 * `C:\Users\DJI\Desktop\red note mediacrawler\MediaCrawler-main\config\base_config.py`，
 * 必须先实现备份、路径白名单和人工确认开关。</p>
 */
@Component
public class MediacrawlerConfigWriter {

    /** 用户本机 MediaCrawler 当前 base_config.py 的默认路径，仅用于提示和预览。 */
    public static final String DEFAULT_BASE_CONFIG_PATH =
            "C:\\Users\\DJI\\Desktop\\red note mediacrawler\\MediaCrawler-main\\config\\base_config.py";

    /**
     * 渲染 MediaCrawler KEYWORDS 配置片段。
     *
     * <p>MediaCrawler 当前使用英文逗号分隔的字符串，因此这里会清理关键词中的英文逗号、
     * 换行和双引号，避免破坏 Python 字符串。</p>
     *
     * @param keywords 待写入 KEYWORDS 的关键词
     * @return 可人工复制到 base_config.py 的配置片段
     */
    public String renderKeywordsConfig(List<String> keywords) {
        List<String> safeKeywords = sanitizeKeywords(keywords);
        String joined = String.join(",", safeKeywords);
        return """
                # Generated by AgentProjectTrip. Please review before applying.
                # Source: RAG POI catalog -> MediaCrawler keyword task.
                # Compliance note: keep small batch, low frequency, and respect platform terms.
                KEYWORDS = "%s"  # 关键词搜索配置，使用英文逗号分隔
                """.formatted(joined);
    }

    /**
     * 清洗关键词，确保它们可以安全放进 Python 双引号字符串。
     */
    public List<String> sanitizeKeywords(List<String> keywords) {
        List<String> sanitized = new ArrayList<>();
        if (keywords == null) {
            return sanitized;
        }
        for (String keyword : keywords) {
            String clean = sanitizeKeyword(keyword);
            if (clean != null && !sanitized.contains(clean)) {
                sanitized.add(clean);
            }
        }
        return sanitized;
    }

    private static String sanitizeKeyword(String keyword) {
        if (keyword == null || keyword.isBlank()) {
            return null;
        }
        String clean = keyword.trim()
                .replace(',', ' ')
                .replace('，', ' ')
                .replace('"', ' ')
                .replace('\n', ' ')
                .replace('\r', ' ')
                .replaceAll("\\s+", " ");
        return clean.isBlank() ? null : clean;
    }
}
